apiVersion: apps/v1
#The kind of k8s object
kind: Deployment
#Cluster identification
metadata:
  name: server-deployment
spec:
  # The number of pod intances replicas
  replicas: 3
  selector:
    # Match the pod template here with template->metadata->labels->component
    matchLabels:
      component: server
   #The pod template. It defines the pod that the deployment has to run.
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: jsrfntd/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              # The secret has to be set in the EKS GCP console. See the readme file for more information.
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD